export enum NAVIGATION_KEYS {
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
	SUCCESSFUL_REGISTRATION = 'SUCCESSFUL_REGISTRATION',
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.REGISTER]: undefined;
	[NAVIGATION_KEYS.EMAIL_VERIFICATION]: undefined;
	[NAVIGATION_KEYS.SUCCESSFUL_REGISTRATION]: undefined;
};
